# Generated by Django 4.2.11 on 2024-05-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='genres',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='filmwork',
            old_name='person',
            new_name='person_id',
        ),
    ]
