# Generated by Django 4.2.11 on 2024-05-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_filmwork_description_alter_filmwork_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='file path'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
