FROM python:3.8-slim
WORKDIR /src

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY src/requirements.txt requirements.txt
RUN python3.8 -m pip install --no-cache-dir --upgrade pip &&\
    python3.8 -m pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "run_buckend.py"]